/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package iodegree;

import iodegree.lib.database.LegacyDB;
import iodegree.lib.MyTableModel;
import iodegree.dataStrucure.BatchNInterest;
import iodegree.lib.CommonsLib;
import java.io.File;
import java.sql.Date;
import java.util.ArrayList;
import java.util.StringTokenizer;
import org.apache.commons.math3.stat.descriptive.SummaryStatistics;

/**
 *
 * @author Libra
 */
public class DistNDivUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public DistNDivUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gluGABAGroup = new javax.swing.ButtonGroup();
        DataFileChooser = new javax.swing.JFileChooser();
        mainScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        rdoGABAOnGlu = new javax.swing.JRadioButton();
        rdoGABAOnGABA = new javax.swing.JRadioButton();
        btnOpenDbDefault = new javax.swing.JButton();
        rdoGluOnGlu = new javax.swing.JRadioButton();
        btnOpenDatabase = new javax.swing.JButton();
        rdoGluOnGABA = new javax.swing.JRadioButton();
        binsScrollPane = new javax.swing.JScrollPane();
        txtBins = new javax.swing.JTextArea();
        chkSepPost = new javax.swing.JCheckBox();
        statsScrollPane = new javax.swing.JScrollPane();
        statsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblOpenDatabase = new javax.swing.JLabel();
        btnQuery = new javax.swing.JButton();
        lblQueryOption = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        resultTable.setModel(new MyTableModel(mainTableData));
        mainScrollPane.setViewportView(resultTable);

        mainScrollPane.setColumnHeaderView(null);

        gluGABAGroup.add(rdoGABAOnGlu);
        rdoGABAOnGlu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoGABAOnGlu.setText("GABA On Glu");
        rdoGABAOnGlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGABAOnGluActionPerformed(evt);
            }
        });

        gluGABAGroup.add(rdoGABAOnGABA);
        rdoGABAOnGABA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoGABAOnGABA.setText("GABA On GABA");
        rdoGABAOnGABA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGABAOnGABAActionPerformed(evt);
            }
        });

        btnOpenDbDefault.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOpenDbDefault.setText("Default");
        btnOpenDbDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDbDefaultActionPerformed(evt);
            }
        });

        gluGABAGroup.add(rdoGluOnGlu);
        rdoGluOnGlu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoGluOnGlu.setSelected(true);
        rdoGluOnGlu.setText("Glu On Glu");
        rdoGluOnGlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGluOnGluActionPerformed(evt);
            }
        });

        btnOpenDatabase.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOpenDatabase.setText("Open");
        btnOpenDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDatabaseActionPerformed(evt);
            }
        });

        gluGABAGroup.add(rdoGluOnGABA);
        rdoGluOnGABA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoGluOnGABA.setText("Glu On GABA");
        rdoGluOnGABA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGluOnGABAActionPerformed(evt);
            }
        });

        txtBins.setColumns(5);
        txtBins.setRows(5);
        txtBins.setText("50\n100\n150\n200\n250\n300\n350");
        binsScrollPane.setViewportView(txtBins);

        chkSepPost.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkSepPost.setSelected(true);
        chkSepPost.setText("Seperate Post Type");
        chkSepPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSepPostActionPerformed(evt);
            }
        });

        statsTable.setModel(new MyTableModel(statsTableData));
        statsScrollPane.setViewportView(statsTable);

        statsScrollPane.setColumnHeaderView(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Bins");

        lblOpenDatabase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpenDatabase.setText("1. Open Database File :");

        btnQuery.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQuery.setText("Query");
        btnQuery.setEnabled(false);
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });

        lblQueryOption.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQueryOption.setText("2. Query Option:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblOpenDatabase)
                                .addComponent(lblQueryOption))
                            .addGap(23, 23, 23))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(34, 34, 34)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(binsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statsScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOpenDatabase)
                                .addGap(18, 18, 18)
                                .addComponent(btnOpenDbDefault))
                            .addComponent(btnQuery))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoGluOnGlu)
                        .addGap(18, 18, 18)
                        .addComponent(rdoGluOnGABA)
                        .addGap(18, 18, 18)
                        .addComponent(rdoGABAOnGlu)
                        .addGap(18, 18, 18)
                        .addComponent(rdoGABAOnGABA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(chkSepPost)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblQueryOption))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOpenDatabase)
                            .addComponent(btnOpenDatabase)
                            .addComponent(btnOpenDbDefault))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rdoGluOnGlu)
                            .addComponent(rdoGABAOnGlu)
                            .addComponent(rdoGABAOnGABA)
                            .addComponent(rdoGluOnGABA)
                            .addComponent(chkSepPost))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuery)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(binsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(statsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoGABAOnGluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoGABAOnGluActionPerformed
        fwGlu = false;
        revGlu = true;
    }//GEN-LAST:event_rdoGABAOnGluActionPerformed

    private void rdoGABAOnGABAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoGABAOnGABAActionPerformed
        fwGlu = false;
        revGlu = false;
//        gluTransfer = false;
//        txtBinSize.setText("12");
    }//GEN-LAST:event_rdoGABAOnGABAActionPerformed

    private void btnOpenDbDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDbDefaultActionPerformed
        pathToFile = CommonsLib.getDefaultFile();
        btnQuery.setEnabled(true);
    }//GEN-LAST:event_btnOpenDbDefaultActionPerformed

    private void rdoGluOnGluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoGluOnGluActionPerformed
        fwGlu = true;
        revGlu = true;
//        gluTransfer = true;
//        txtBinSize.setText("23");
    }//GEN-LAST:event_rdoGluOnGluActionPerformed

    private void btnOpenDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDatabaseActionPerformed
        int returnVal = DataFileChooser.showOpenDialog(this);
        if (returnVal == DataFileChooser.APPROVE_OPTION) {
            pathToFile = DataFileChooser.getSelectedFile().getAbsolutePath();
//            System.out.println("File " + pathToFile + " opened.");
            btnQuery.setEnabled(true);
        }
    }//GEN-LAST:event_btnOpenDatabaseActionPerformed

    private void rdoGluOnGABAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoGluOnGABAActionPerformed
        fwGlu = true;
        revGlu = false;
    }//GEN-LAST:event_rdoGluOnGABAActionPerformed

    private void chkSepPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSepPostActionPerformed
        if (chkSepPost.isSelected()) {
            boolSepPost = true;
            rdoGluOnGlu.setText("Glu On Glu");
            rdoGABAOnGlu.setText("GABA On Glu");
            rdoGluOnGABA.setVisible(true);
            rdoGABAOnGABA.setVisible(true);

        } else {
            boolSepPost = false;
            rdoGluOnGlu.setText("Glu");
            rdoGABAOnGlu.setText("GABA");
            rdoGluOnGABA.setVisible(false);
            rdoGABAOnGABA.setVisible(false);
        }
    }//GEN-LAST:event_chkSepPostActionPerformed

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed


        /*
         * get slot list and con list with dist
         */
        lstSlot = LegacyDB.slotWDivQry(pathToFile, boolSepPost, fwGlu, revGlu, "dist");
        lstConn = LegacyDB.connWDivQry(pathToFile, boolSepPost, fwGlu, revGlu, "dist");

        sumUp();

        MyTableModel mainTableModel = new MyTableModel(mainTableData);
        MyTableModel statsTableModel = new MyTableModel(statsTableData);
        mainScrollPane.setColumnHeaderView(null);
        statsScrollPane.setColumnHeaderView(null);
        resultTable.setModel(mainTableModel);
        statsTable.setModel(statsTableModel);
//        btnIO.setEnabled(true);
    }//GEN-LAST:event_btnQueryActionPerformed

    private void sumUp() {

        //TODO proper build distBin;
        distBin = getBin();

        /*
         * Dispatch slots;
         */
        Integer[] bin = new Integer[distBin.size() + 1];
        for (int i = 0; i < bin.length; i++) {
            bin[i] = new Integer(0);
        }
        ArrayList<Integer[]> slotByBatch = new ArrayList<>(30);
        int currDiv = 0;

        for (int i = 0; i < lstSlot.size();) {
            if (currDiv == lstSlot.get(i).getDiv()) {
                bin[dispatch(lstSlot.get(i).getInterest())]++;
                i++;
            } else {
                currDiv = lstSlot.get(i).getDiv();
//                System.out.println(currDate);
                slotByBatch.add(bin);
                bin = new Integer[distBin.size() + 1];
                for (int j = 0; j < bin.length; j++) {
                    bin[j] = new Integer(0);
                };
            }
        }
        slotByBatch.add(bin);

        /*
         * Dispatch connects
         */
        ArrayList<Integer[]> connByBatch = new ArrayList<>(30);
        currDiv = 0;

        for (int i = 0; i < lstConn.size();) {
            System.out.println(lstConn.get(i).getDiv());
            if (currDiv == lstConn.get(i).getDiv()) {
                bin[dispatch(lstConn.get(i).getInterest())]++;
                i++;
            } else {
                currDiv = lstConn.get(i).getDiv();
//                System.out.println(currDate);
                connByBatch.add(bin);
                bin = new Integer[distBin.size() + 1];
                for (int j = 0; j < bin.length; j++) {
                    bin[j] = new Integer(0);
                };
            }
        }
        connByBatch.add(bin);

        /*
         * Calc Ratio, fill table
         */
        mainTableData = new Object[slotByBatch.size()][distBin.size()];
        if (connByBatch.size() == slotByBatch.size()) {
            for (int i = 0; i < slotByBatch.size(); i++) {
                for (int j = 0; j < distBin.size(); j++) {
                    mainTableData[i][j] = (slotByBatch.get(i)[j] == 0)
                            ? null
                            : new Float((float) connByBatch.get(i)[j] / slotByBatch.get(i)[j]);
                }
            }
        } else {
            System.out.println("Batch Size Don't Match");
            mainTableData = new Object[slotByBatch.size()][distBin.size()];
        }

        /*
         * fill top row and left column
         */
        for (int i = 0; i < distBin.size(); i++) {

            mainTableData[0][i] = "UpTo" + distBin.get(i).toString();
        }

        /*
         * Fill statistics table
         */
        statsTableData = new Object[3][distBin.size()];
        for (int i = 0; i < distBin.size(); i++) {
            SummaryStatistics stats = new SummaryStatistics();
            for (int j = 1; j < slotByBatch.size(); j++) {
                if (mainTableData[j][i] == null) {
//                    System.out.println("null!");
                } else {
                    stats.addValue(
                            Double.parseDouble(mainTableData[j][i].toString()));
                }
            }
            statsTableData[0][i] = new Double(stats.getMean());
            statsTableData[1][i] = new Double(stats.getStandardDeviation());
            statsTableData[2][i] = new Double(
                    stats.getStandardDeviation() / Math.sqrt(stats.getN() - 1));
        }

    }

    private int dispatch(int dist) {
        for (int i = 0; i < distBin.size();) {
//            System.out.println(dist+","+distTop.get(i));
            if (dist > distBin.get(i)) {
                i++;
            } else {
//                System.out.println(i);
                return i;
            }
        }
//        System.out.println(distTop.size());
        return distBin.size();
    }

    private ArrayList<Integer> getBin() {
        ArrayList<Integer> bin = new ArrayList<>(10);
        StringTokenizer st = new StringTokenizer(txtBins.getText());
        while (st.hasMoreTokens()) {
            bin.add(Integer.parseInt(st.nextToken()));
        }
        return bin;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistNDivUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistNDivUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistNDivUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistNDivUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DistNDivUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser DataFileChooser;
    private javax.swing.JScrollPane binsScrollPane;
    private javax.swing.JButton btnOpenDatabase;
    private javax.swing.JButton btnOpenDbDefault;
    private javax.swing.JButton btnQuery;
    private javax.swing.JCheckBox chkSepPost;
    private javax.swing.ButtonGroup gluGABAGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblOpenDatabase;
    private javax.swing.JLabel lblQueryOption;
    private javax.swing.JScrollPane mainScrollPane;
    private javax.swing.JRadioButton rdoGABAOnGABA;
    private javax.swing.JRadioButton rdoGABAOnGlu;
    private javax.swing.JRadioButton rdoGluOnGABA;
    private javax.swing.JRadioButton rdoGluOnGlu;
    private javax.swing.JTable resultTable;
    private javax.swing.JScrollPane statsScrollPane;
    private javax.swing.JTable statsTable;
    private javax.swing.JTextArea txtBins;
    // End of variables declaration//GEN-END:variables
    private String pathToFile;
    private boolean fwGlu = true;
    private boolean revGlu = true;
    private ArrayList<BatchNInterest> lstSlot;
    private ArrayList<BatchNInterest> lstConn;
    private ArrayList<Integer> distBin;
    private Object[][] mainTableData = new Object[20][12];
    private Object[][] statsTableData = new Object[3][12];
    private boolean boolSepPost = true;
}
