/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package iodegree;

import iodegree.dataStrucure.BatchRatio;
import iodegree.lib.MyTableModel;
import iodegree.lib.CommonsLib;
import iodegree.lib.D;
import iodegree.lib.database.DBHandle;
import java.util.ArrayList;
import org.apache.commons.math3.stat.descriptive.SummaryStatistics;

/**
 *
 * @author Libra
 */
public class DIVStatsUI extends javax.swing.JFrame {

    /**
     * Creates new form DIVStats
     */
    public DIVStatsUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gluGABAGroup = new javax.swing.ButtonGroup();
        DataFileChooser = new javax.swing.JFileChooser();
        btnQuery = new javax.swing.JButton();
        lblQueryOption = new javax.swing.JLabel();
        lblOpenDatabase = new javax.swing.JLabel();
        chkSepPost = new javax.swing.JCheckBox();
        rdoGABAOnGlu = new javax.swing.JRadioButton();
        rdoGABAOnGABA = new javax.swing.JRadioButton();
        mainScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        btnOpenDbDefault = new javax.swing.JButton();
        rdoGluOnGlu = new javax.swing.JRadioButton();
        btnOpenDatabase = new javax.swing.JButton();
        rdoGluOnGABA = new javax.swing.JRadioButton();
        statsScrollPane = new javax.swing.JScrollPane();
        statsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnQuery.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQuery.setText("Query");
        btnQuery.setEnabled(false);
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });

        lblQueryOption.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQueryOption.setText("2. Query Option:");

        lblOpenDatabase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOpenDatabase.setText("1. Open Database File :");

        chkSepPost.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkSepPost.setSelected(true);
        chkSepPost.setText("Seperate Post Type");
        chkSepPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSepPostActionPerformed(evt);
            }
        });

        gluGABAGroup.add(rdoGABAOnGlu);
        rdoGABAOnGlu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoGABAOnGlu.setText("GABA On Glu");
        rdoGABAOnGlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGABAOnGluActionPerformed(evt);
            }
        });

        gluGABAGroup.add(rdoGABAOnGABA);
        rdoGABAOnGABA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoGABAOnGABA.setText("GABA On GABA");
        rdoGABAOnGABA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGABAOnGABAActionPerformed(evt);
            }
        });

        mainScrollPane.setViewportView(resultTable);

        mainScrollPane.setColumnHeaderView(null);

        btnOpenDbDefault.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOpenDbDefault.setText("Default");
        btnOpenDbDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDbDefaultActionPerformed(evt);
            }
        });

        gluGABAGroup.add(rdoGluOnGlu);
        rdoGluOnGlu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoGluOnGlu.setSelected(true);
        rdoGluOnGlu.setText("Glu On Glu");
        rdoGluOnGlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGluOnGluActionPerformed(evt);
            }
        });

        btnOpenDatabase.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOpenDatabase.setText("Open");
        btnOpenDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDatabaseActionPerformed(evt);
            }
        });

        gluGABAGroup.add(rdoGluOnGABA);
        rdoGluOnGABA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoGluOnGABA.setText("Glu On GABA");
        rdoGluOnGABA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGluOnGABAActionPerformed(evt);
            }
        });

        statsScrollPane.setViewportView(statsTable);

        statsScrollPane.setColumnHeaderView(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOpenDatabase)
                    .addComponent(lblQueryOption))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statsScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOpenDatabase)
                                .addGap(18, 18, 18)
                                .addComponent(btnOpenDbDefault))
                            .addComponent(btnQuery))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoGluOnGlu)
                        .addGap(18, 18, 18)
                        .addComponent(rdoGluOnGABA)
                        .addGap(18, 18, 18)
                        .addComponent(rdoGABAOnGlu)
                        .addGap(18, 18, 18)
                        .addComponent(rdoGABAOnGABA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(chkSepPost)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblQueryOption))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOpenDatabase)
                            .addComponent(btnOpenDatabase)
                            .addComponent(btnOpenDbDefault))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rdoGluOnGlu)
                            .addComponent(rdoGABAOnGlu)
                            .addComponent(rdoGABAOnGABA)
                            .addComponent(rdoGluOnGABA)
                            .addComponent(chkSepPost))))
                .addGap(18, 18, 18)
                .addComponent(btnQuery)
                .addGap(18, 18, 18)
                .addComponent(mainScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed

        /*
         * get slot list and con list with dist
         */
        DBHandle db = new DBHandle();
        BatchRatio ratioes = new BatchRatio();
        ratioes.setBins(getBins());
//        D.tp(pathToFile);
        db.ratioBatches(pathToFile, boolSepPost, fwGlu, revGlu, "DIV", ratioes);
//        D.p(Arrays.deepToString(ratioes.getBatchRatio()));
        Object[][] ratioTabD;
        ratioes.genBatchRatio();
        ratioTabD = new Object[ratioes.getBatches().size() + 1][ratioes.getBins().size() + 1];
        for (int i = 1; i < ratioTabD.length; i++) {
            ratioTabD[i][0] = ratioes.getBatches().get(i - 1);
            System.arraycopy(ratioes.getBatchRatio()[i - 1], 0, ratioTabD[i], 1, ratioes.getBins().size());
        }

        for (int i = 1; i < ratioTabD[0].length; i++) {
            ratioTabD[0][i] = "DIV" + Integer.toString(ratioes.getBins().get(i - 1));
        }

        MyTableModel mainTableModel = new MyTableModel(ratioTabD);
        mainScrollPane.setColumnHeaderView(null);
        resultTable.setModel(mainTableModel);

        /*
         * Fill statistics table
         */
        Object[][] statsTabD = new Object[3][ratioes.getBins().size() + 1];
        
        for (int i = 0; i < ratioes.getBins().size(); i++) {
            SummaryStatistics stats = new SummaryStatistics();
            for (int j = 0; j < ratioes.getBatches().size(); j++) {
                if (ratioes.getBatchRatio()[j][i] == null) {
//                    System.out.println("null!");
                } else {
                    stats.addValue(ratioes.getBatchRatio()[j][i]);
                }
            }
            statsTabD[0][i + 1] = new Double(stats.getMean());
            statsTabD[1][i + 1] = new Double(stats.getStandardDeviation());
            statsTabD[2][i + 1] = new Double(
                    stats.getStandardDeviation() / Math.sqrt(stats.getN()));
        }
        statsTabD[0][0] = "Mean";
        statsTabD[1][0] = "S.D.";
        statsTabD[2][0] = "S.E.M.";

        MyTableModel statsTableModel = new MyTableModel(statsTabD);
        statsScrollPane.setColumnHeaderView(null);
        statsTable.setModel(statsTableModel);

    }//GEN-LAST:event_btnQueryActionPerformed

    private ArrayList<Integer> getBins() {
        ArrayList<Integer> bin = new ArrayList<>(4);
        for (int i = 5; i < 9; i++) {
            bin.add(i);
        }
        return bin;
    }

    private void chkSepPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSepPostActionPerformed
        if (chkSepPost.isSelected()) {
            boolSepPost = true;
            rdoGluOnGlu.setText("Glu On Glu");
            rdoGABAOnGlu.setText("GABA On Glu");
            rdoGluOnGABA.setVisible(true);
            rdoGABAOnGABA.setVisible(true);

        } else {
            boolSepPost = false;
            rdoGluOnGlu.setText("Glu");
            rdoGABAOnGlu.setText("GABA");
            rdoGluOnGABA.setVisible(false);
            rdoGABAOnGABA.setVisible(false);
        }
    }//GEN-LAST:event_chkSepPostActionPerformed

    private void rdoGABAOnGluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoGABAOnGluActionPerformed
        fwGlu = false;
        revGlu = true;
    }//GEN-LAST:event_rdoGABAOnGluActionPerformed

    private void rdoGABAOnGABAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoGABAOnGABAActionPerformed
        fwGlu = false;
        revGlu = false;
//        gluTransfer = false;
//        txtBinSize.setText("12");
    }//GEN-LAST:event_rdoGABAOnGABAActionPerformed

    private void btnOpenDbDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDbDefaultActionPerformed
        pathToFile = CommonsLib.getDefaultFile();
        btnQuery.setEnabled(true);
    }//GEN-LAST:event_btnOpenDbDefaultActionPerformed

    private void rdoGluOnGluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoGluOnGluActionPerformed
        fwGlu = true;
        revGlu = true;
//        gluTransfer = true;
//        txtBinSize.setText("23");
    }//GEN-LAST:event_rdoGluOnGluActionPerformed

    private void btnOpenDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDatabaseActionPerformed
        int returnVal = DataFileChooser.showOpenDialog(this);
        if (returnVal == DataFileChooser.APPROVE_OPTION) {
            pathToFile = DataFileChooser.getSelectedFile().getAbsolutePath();
//            System.out.println("File " + pathToFile + " opened.");
            btnQuery.setEnabled(true);
        }
    }//GEN-LAST:event_btnOpenDatabaseActionPerformed

    private void rdoGluOnGABAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoGluOnGABAActionPerformed
        fwGlu = true;
        revGlu = false;
    }//GEN-LAST:event_rdoGluOnGABAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DIVStatsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DIVStatsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DIVStatsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DIVStatsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DIVStatsUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser DataFileChooser;
    private javax.swing.JButton btnOpenDatabase;
    private javax.swing.JButton btnOpenDbDefault;
    private javax.swing.JButton btnQuery;
    private javax.swing.JCheckBox chkSepPost;
    private javax.swing.ButtonGroup gluGABAGroup;
    private javax.swing.JLabel lblOpenDatabase;
    private javax.swing.JLabel lblQueryOption;
    private javax.swing.JScrollPane mainScrollPane;
    private javax.swing.JRadioButton rdoGABAOnGABA;
    private javax.swing.JRadioButton rdoGABAOnGlu;
    private javax.swing.JRadioButton rdoGluOnGABA;
    private javax.swing.JRadioButton rdoGluOnGlu;
    private javax.swing.JTable resultTable;
    private javax.swing.JScrollPane statsScrollPane;
    private javax.swing.JTable statsTable;
    // End of variables declaration//GEN-END:variables
    private String pathToFile;
    private boolean fwGlu = true;
    private boolean revGlu = true;
    private boolean boolSepPost = true;
}
