/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package iodegree;

import iodegree.lib.TempTest;
import iodegree.lib.URIHandle;
import iodegree.lib.devpModel.ModelUI;
import iodegree.lib.pattern.ClusterUI;
import iodegree.lib.pattern.PatternUI;
import iodegree.lib.reci.ReciUI;
import iodegree.lib.weight.ClusterWeightUI;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Libra
 */
public class StageUI extends javax.swing.JFrame {

    /**
     * Creates new form stageChooserUI
     */
    public StageUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmail = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnDiv = new javax.swing.JButton();
        btnDistNDiv = new javax.swing.JButton();
        btnDist3 = new javax.swing.JButton();
        btnRecp = new javax.swing.JButton();
        btnIO = new javax.swing.JButton();
        btnSplit = new javax.swing.JButton();
        btnSplit1 = new javax.swing.JButton();
        btnSplit4 = new javax.swing.JButton();
        btnSplit3 = new javax.swing.JButton();
        btnSplit2 = new javax.swing.JButton();
        btnSplit5 = new javax.swing.JButton();
        btnSplit6 = new javax.swing.JButton();
        btnDist5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnDist = new javax.swing.JButton();
        btnDist2 = new javax.swing.JButton();
        btnTempTest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Everything Starts Here");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblEmail.setText("zhangxiaoxing@ion.ac.cn");
        lblEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEmailMouseExited(evt);
            }
        });

        btnDiv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDiv.setText("1. Connection Prob By DIV");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnDistNDiv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDistNDiv.setText("1. Connection Prob By DIV and Dist");
        btnDistNDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistNDivActionPerformed(evt);
            }
        });

        btnDist3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDist3.setText("1. Connection Prob By Dist");
        btnDist3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDist3ActionPerformed(evt);
            }
        });

        btnRecp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRecp.setText("2. Reciprocal Connections");
        btnRecp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecpActionPerformed(evt);
            }
        });

        btnIO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnIO.setText("3.  IO Degree");
        btnIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIOActionPerformed(evt);
            }
        });

        btnSplit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSplit.setText("4. Pattern");
        btnSplit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSplitActionPerformed(evt);
            }
        });

        btnSplit1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSplit1.setText("5. Clustering");
        btnSplit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSplit1ActionPerformed(evt);
            }
        });

        btnSplit4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSplit4.setText("5. Clustering Weight");
        btnSplit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSplit4ActionPerformed(evt);
            }
        });

        btnSplit3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSplit3.setText("5. Quadro Clustering");
        btnSplit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSplit3ActionPerformed(evt);
            }
        });

        btnSplit2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSplit2.setText("6. ChR2 Clustering");
        btnSplit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSplit2ActionPerformed(evt);
            }
        });

        btnSplit5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSplit5.setText("7. Common Neighbor");
        btnSplit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSplit5ActionPerformed(evt);
            }
        });

        btnSplit6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSplit6.setText("Interaction");
        btnSplit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSplit6ActionPerformed(evt);
            }
        });

        btnDist5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDist5.setText("Model");
        btnDist5.setToolTipText("");
        btnDist5.setEnabled(false);
        btnDist5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDist5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIO, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSplit5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDist3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDistNDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRecp, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSplit1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSplit3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSplit2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSplit4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSplit, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSplit6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDist5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDist3)
                    .addComponent(btnSplit1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiv)
                    .addComponent(btnSplit4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDistNDiv)
                    .addComponent(btnSplit3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecp)
                    .addComponent(btnSplit2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIO)
                    .addComponent(btnSplit5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSplit)
                    .addComponent(btnSplit6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDist5)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnDist.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDist.setText("1a. Connection Prob Fits Distance");
        btnDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistActionPerformed(evt);
            }
        });

        btnDist2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDist2.setText("1b. Seperated Connection Prob Fits Distance");
        btnDist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDist2ActionPerformed(evt);
            }
        });

        btnTempTest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTempTest.setText("TEMP TEST");
        btnTempTest.setToolTipText("");
        btnTempTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTempTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDist, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTempTest, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDist2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDist)
                    .addComponent(btnTempTest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDist2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblEmail))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIOActionPerformed
        JFrame ui = new IO();
        ui.setVisible(true);
    }//GEN-LAST:event_btnIOActionPerformed

    private void btnDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistActionPerformed
        JFrame ui = new DistUI();
        ui.setVisible(true);
    }//GEN-LAST:event_btnDistActionPerformed

    private void btnDist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDist2ActionPerformed
        JFrame ui = new DistUI2();
        ui.setVisible(true);
    }//GEN-LAST:event_btnDist2ActionPerformed

    private void btnDist3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDist3ActionPerformed
        JFrame ui = new DistStatsUI();
        ui.setVisible(true);
    }//GEN-LAST:event_btnDist3ActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        JFrame ui = new DIVStatsUI();
        ui.setVisible(true);
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnDistNDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistNDivActionPerformed
        JFrame ui = new DistNDivUI();
        ui.setVisible(true);
    }//GEN-LAST:event_btnDistNDivActionPerformed

    private void btnRecpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecpActionPerformed
        JFrame ui = new ReciUI();
        ui.setVisible(true);
    }//GEN-LAST:event_btnRecpActionPerformed

    private void lblEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmailMouseClicked
        URIHandle.mailme();
    }//GEN-LAST:event_lblEmailMouseClicked

    private void lblEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmailMouseEntered
        lblEmail.setForeground(Color.BLUE);
    }//GEN-LAST:event_lblEmailMouseEntered

    private void lblEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmailMouseExited
        lblEmail.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblEmailMouseExited

    private void btnSplitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSplitActionPerformed
        JFrame ui = new PatternUI();
        ui.setVisible(true);
    }//GEN-LAST:event_btnSplitActionPerformed

    private void btnSplit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSplit1ActionPerformed
        JFrame ui = new ClusterUI();
        ui.setVisible(true);
    }//GEN-LAST:event_btnSplit1ActionPerformed

    private void btnSplit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSplit2ActionPerformed
        JFrame ui = new ChR2ClusterUI();
        ui.setVisible(true);
    }//GEN-LAST:event_btnSplit2ActionPerformed

    private void btnSplit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSplit3ActionPerformed
        JFrame ui = new ClusterQuadroUI();
        ui.setVisible(true);
    }//GEN-LAST:event_btnSplit3ActionPerformed

    private void btnSplit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSplit4ActionPerformed
        JFrame ui = new ClusterWeightUI();
        ui.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSplit4ActionPerformed

    private void btnSplit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSplit5ActionPerformed
        JFrame ui = new CommonNeighborUI();
        ui.setVisible(true);
    }//GEN-LAST:event_btnSplit5ActionPerformed

    private void btnTempTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTempTestActionPerformed
        TempTest tt = new TempTest();
    }//GEN-LAST:event_btnTempTestActionPerformed

    private void btnSplit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSplit6ActionPerformed
        JFrame ui = new iodegree.interact.InteractUI();
        ui.setVisible(true);
    }//GEN-LAST:event_btnSplit6ActionPerformed

    private void btnDist5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDist5ActionPerformed
        JFrame ui = new ModelUI(); 
        ui.setVisible(true);
    }//GEN-LAST:event_btnDist5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new StageUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDist;
    private javax.swing.JButton btnDist2;
    private javax.swing.JButton btnDist3;
    private javax.swing.JButton btnDist5;
    private javax.swing.JButton btnDistNDiv;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnIO;
    private javax.swing.JButton btnRecp;
    private javax.swing.JButton btnSplit;
    private javax.swing.JButton btnSplit1;
    private javax.swing.JButton btnSplit2;
    private javax.swing.JButton btnSplit3;
    private javax.swing.JButton btnSplit4;
    private javax.swing.JButton btnSplit5;
    private javax.swing.JButton btnSplit6;
    private javax.swing.JButton btnTempTest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEmail;
    // End of variables declaration//GEN-END:variables
}
